name: Deploy Docusaurus site

on:
  push:
    branches:
      - docusaurusO  # 确保与您主要开发分支一致

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22'  # 可根据需要调整版本号

    - name: Install dependencies
      run: npm install

    - name: Build Docusaurus
      run: npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build  # 默认输出到 build 文件夹